{% set name = "opentelemetry-semantic-conventions" %}
{% set version = "0.35b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-semantic-conventions-{{ version }}.tar.gz
  sha256: 3c24717f2838a6b4db45d68abf69078942e876c2347e0a83a09c1533017d85d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - hatchling
  run:
    - python >=3.7,<3.11
    - opentelemetry-api >=1.12,<2.dev0

test:
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  summary: OpenTelemetry Semantic Conventions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - rxm7706
    - cshaley
